version: '3'

services:
  app:
    image: nextjs-app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app