version: '3.8'

services:
  app:
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pgWithNest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
