version: '3.8'

services:
  app:
    image: nextjs-app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    env_file:
      - .env

volumes:
  postgres_data:
  postgres_logs:
