version: '3'

services:
  app:
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app